import { act, create, type ReactTestRenderer } from 'react-test-renderer';
import { beforeEach, expect, it, vi } from 'vitest';
import PrintDialog from './PrintDialog';
import { cancelPrint, printDocument, type PrintResult } from './bridge';
import type { DocumentInfo } from './model';
vi.mock('./bridge', () => ({ printDocument: vi.fn(), cancelPrint: vi.fn() }));
const document: DocumentInfo = { id: 8, name: 'edited.pdf', path: 'edited.pdf', pages: [{ width: 612, height: 792 }], revision: 3, dirty: true, can_undo: true, can_redo: false };
beforeEach(() => { vi.clearAllMocks(); vi.mocked(cancelPrint).mockResolvedValue(); });
it('prints the current revision, prevents duplicate requests and reports submission without claiming physical completion', async () => {
  let resolve!: (result: PrintResult) => void;
  vi.mocked(printDocument).mockImplementation(() => new Promise(done => { resolve = done; }));
  const setBusy = vi.fn(), close = vi.fn(); let ui!: ReactTestRenderer;
  act(() => { ui = create(<PrintDialog document={document} page={0} setBusy={setBusy} close={close} />); });
  act(() => { ui.root.findAllByType('button')[1].props.onClick(); ui.root.findAllByType('button')[1].props.onClick(); });
  expect(printDocument).toHaveBeenCalledOnce();
  expect(printDocument).toHaveBeenCalledWith(8, 3, 0, expect.any(String));
  expect(ui.root.findAllByType('button')[1].props.disabled).toBe(true);
  await act(async () => resolve({ status: 'submitted', pages: 1 }));
  expect(setBusy.mock.calls).toEqual([[true], [false]]);
  expect(JSON.stringify(ui.toJSON())).toContain('submitted to the printer');
  expect(close).not.toHaveBeenCalled();
  act(() => ui.unmount());
});
it('routes cancellation to the active job and waits for its result before releasing busy state', async () => {
  let resolve!: (result: PrintResult) => void;
  vi.mocked(printDocument).mockImplementation(() => new Promise(done => { resolve = done; }));
  const setBusy = vi.fn(), close = vi.fn(); let ui!: ReactTestRenderer;
  act(() => { ui = create(<PrintDialog document={document} page={0} setBusy={setBusy} close={close} />); });
  act(() => ui.root.findAllByType('button')[1].props.onClick());
  await act(async () => ui.root.findByType('dialog').props.onCancel({ preventDefault: vi.fn() }));
  expect(cancelPrint).toHaveBeenCalledWith(vi.mocked(printDocument).mock.calls[0][3]);
  expect(close).not.toHaveBeenCalled(); expect(setBusy.mock.calls).toEqual([[true]]);
  await act(async () => resolve({ status: 'cancelled' }));
  expect(setBusy).toHaveBeenLastCalledWith(false);
  expect(JSON.stringify(ui.toJSON())).toContain('Printing canceled');
  act(() => ui.unmount());
});
it('releases the busy guard after failure and allows retry', async () => {
  vi.mocked(printDocument).mockRejectedValueOnce(new Error('printer offline')).mockResolvedValueOnce({ status: 'cancelled' });
  const setBusy = vi.fn(); let ui!: ReactTestRenderer;
  act(() => { ui = create(<PrintDialog document={document} page={0} setBusy={setBusy} close={vi.fn()} />); });
  await act(async () => ui.root.findAllByType('button')[1].props.onClick());
  expect(JSON.stringify(ui.toJSON())).toContain('printer offline');
  expect(setBusy).toHaveBeenLastCalledWith(false);
  await act(async () => ui.root.findAllByType('button')[1].props.onClick());
  expect(printDocument).toHaveBeenCalledTimes(2);
  expect(ui.root.findAllByProps({ role: 'alert' })).toHaveLength(0);
  act(() => ui.unmount());
});
it('ignores cancellation responses that arrive after the job has completed', async () => {
  let finish!: (result: PrintResult) => void, cancelDone!: () => void;
  vi.mocked(printDocument).mockImplementation(() => new Promise(done => { finish = done; }));
  vi.mocked(cancelPrint).mockImplementation(() => new Promise(done => { cancelDone = done; }));
  let ui!: ReactTestRenderer;
  act(() => { ui = create(<PrintDialog document={document} page={0} setBusy={vi.fn()} close={vi.fn()} />); });
  act(() => ui.root.findAllByType('button')[1].props.onClick());
  act(() => ui.root.findAllByType('button')[0].props.onClick());
  await act(async () => finish({ status: 'submitted', pages: 1 }));
  await act(async () => cancelDone());
  expect(JSON.stringify(ui.toJSON())).toContain('submitted to the printer');
  expect(JSON.stringify(ui.toJSON())).not.toContain('Cancel requested');
  act(() => ui.unmount());
});
